cargo-features=["edition"]

[package]
name = "async_await"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>", "Taylor Cramer <cramertj@google.com>"]
edition = '2018'

[[bin]]
path = "src/timer.rs"
name = "timer"
